type Restaurant {
  id: ID!
  name: String!
  description: String!
  address: String!
  type: RestaurantType!
  openingHours: OpeningHours!
  phoneNumber: String!
  email: String!
  rating: Float
  imageUrl: String
  isActive: Boolean
  createdAt: String!
  updatedAt: String!
}
type MenuItem {
  id: ID!
  name: String!
  description: String
  price: Float!
  restaurantId: ID!
  imageUrl: String
  category: String! # Add category field
  createdAt: String
  updatedAt: String
}

enum RestaurantType {
  RESTAURANT
  BOULANGERIE
  EXPRESS
}

type OpeningHours {
  monday: DailyHours!
  tuesday: DailyHours!
  wednesday: DailyHours!
  thursday: DailyHours!
  friday: DailyHours!
  saturday: DailyHours!
  sunday: DailyHours!
}

type DailyHours {
  open: String!
  close: String!
}

type Query {
  restaurants: [Restaurant!]!
  restaurant(id: ID!): Restaurant
  searchRestaurants(query: String!): [Restaurant!]!
  menuItems(restaurantId: ID!): [MenuItem!]!
}

type Mutation {
  createRestaurant(input: CreateRestaurantInput!): Restaurant!
  updateRestaurant(id: ID!, input: UpdateRestaurantInput!): Restaurant!
  deleteRestaurant(id: ID!): Boolean!
  addMenuItem(input: AddMenuItemInput!): MenuItem!
}

input CreateRestaurantInput {
  name: String!
  description: String!
  address: String!
  type: RestaurantType!
  openingHours: OpeningHoursInput!
  phoneNumber: String!
  email: String!
  imageUrl: String
  isActive: Boolean
}

input UpdateRestaurantInput {
  name: String
  description: String
  address: String
  type: RestaurantType
  openingHours: OpeningHoursInput
  phoneNumber: String
  email: String
  imageUrl: String
  isActive: Boolean
}

input OpeningHoursInput {
  monday: DailyHoursInput!
  tuesday: DailyHoursInput!
  wednesday: DailyHoursInput!
  thursday: DailyHoursInput!
  friday: DailyHoursInput!
  saturday: DailyHoursInput!
  sunday: DailyHoursInput!
}

input DailyHoursInput {
  open: String!
  close: String!
}

input AddMenuItemInput {
  name: String!
  description: String
  price: Float!
  restaurantId: ID!
  category: String!
  imageUrl: String
}
