type User {
  id: ID!
  name: String!
  phoneNumber: String!
  password: String!
  createdAt: String!
  role: UserType!
  profilePicture: String
}
type Restaurant {
  id: ID!
  name: String!
  description: String!
  address: String!
  type: RestaurantType!
  openingHours: OpeningHours!
  phoneNumber: String!
  email: String!
  rating: Float
  imageUrl: String
  isActive: Boolean
  createdAt: String!
  updatedAt: String!
}
type MenuItem {
  id: ID!
  name: String!
  description: String
  price: Float!
  restaurantId: ID!
  imageUrl: String
  category: String! # Add category field
  isAvailable: Boolean
  createdAt: String
  updatedAt: String
}

enum UserType {
  deliverer
  customer
  admin
  guest
}

enum RestaurantType {
  RESTAURANT
  BOULANGERIE
  EXPRESS
}

type OpeningHours {
  monday: DailyHours!
  tuesday: DailyHours!
  wednesday: DailyHours!
  thursday: DailyHours!
  friday: DailyHours!
  saturday: DailyHours!
  sunday: DailyHours!
}

type Address {
  address: String!
  latitude: Float!
  longitude: Float!
}

type DailyHours {
  open: String!
  close: String!
}

type Order {
  id: ID!
  restaurantId: ID!
  userId: ID!
  user: User
  restaurant: Restaurant # Added restaurant field
  items: [OrderItem]!
  totalAmount: Float!
  deliveryAddress: Address
  instructions: String
  status: OrderStatus!
  isPaid: Boolean!
  paymentMethod: PaymentMethod!
  createdAt: String!
  updatedAt: String!
  delivererId: ID # Added delivererId field
  deliverer: Deliverer # Added deliverer field
}

type OrderItem {
  menuItemId: ID!
  menuItem: MenuItem
  quantity: Int!
  price: Float!
}

enum OrderStatus {
  Pending
  PREPARING
  DELIVERING
  COMPLETED
  CANCELLED
}

enum PaymentMethod {
  CASH
  ORANGE_MONEY
  WAVE
}

type Deliverer {
  userId: ID!
  user: User
  vehicleId: ID
  isAvailable: Boolean!
  currentLocation: Address
  zone: String
  profilePicture: String
  isActive: Boolean!
  isVerified: Boolean!
}

type Notification {
  id: ID!
  userId: ID!
  title: String!
  body: String!
  read: Boolean!
  createdAt: String!
}

type Query {
  users: [User!]!
  user(id: ID!): User
  restaurants: [Restaurant!]!
  restaurant(id: ID!): Restaurant
  searchRestaurants(query: String!): [Restaurant!]!
  menuItems(restaurantId: ID!): [MenuItem!]!
  menuItem(id: ID!): MenuItem
  allMenuItems: [MenuItem!]!
  orders(userId: ID, restaurantId: ID, status: String, delivererId: ID): [Order!]!
  order(id: ID!): Order
  deliverer(id: ID!): Deliverer
  delivererByUserId(userId: ID!): Deliverer
  allDeliverers: [Deliverer!]!
  availableDeliverers: [Deliverer!]!
  restaurantByEmail(email: String!): Restaurant
  notifications(userId: ID!): [Notification!]!
}

type Mutation {
  createUser(input: CreateUserInput!): User!
  updateUser(id: ID!, input: UpdateUserInput!): User!
  createRestaurant(input: CreateRestaurantInput!): Restaurant!
  updateRestaurant(id: ID!, input: UpdateRestaurantInput!): Restaurant!
  deleteRestaurant(id: ID!): Boolean!
  addMenuItem(input: AddMenuItemInput!): MenuItem!
  updateMenuItem(id: ID!, input: UpdateMenuItemInput!): MenuItem!
  deleteMenuItem(id: ID!): Boolean!
  createOrder(input: OrderInput!): Order!
  updateOrderStatus(id: ID!, status: OrderStatus!): Order!
  createDeliverer(input: CreateDelivererInput!): Deliverer!
  updateDelivererStatus(userId: ID!, isAvailable: Boolean!): Deliverer!
  updateDelivererLocation(userId: ID!, location: LocationInput!): Deliverer!
  deleteUser(id: ID!): Boolean!
  markNotificationAsRead(id: ID!): Notification!
  markAllNotificationsAsRead(userId: ID!): Boolean!
  confirmOrderDelivery(orderId: ID!, token: String!, delivererId: ID!): Order!
  manualConfirmDelivery(orderId: ID!, delivererId: ID!): Order!
}

input CreateUserInput {
  name: String!
  phoneNumber: String!
  role: UserType!
}

input LocationInput {
  address: String!
  latitude: Float!
  longitude: Float!
}

input UpdateUserInput {
  name: String
  password: String
  profilePicture: String
}

input CreateRestaurantInput {
  name: String!
  description: String!
  address: String!
  type: RestaurantType!
  openingHours: OpeningHoursInput!
  phoneNumber: String!
  email: String!
  imageUrl: String
  isActive: Boolean
}

input UpdateRestaurantInput {
  name: String
  description: String
  address: String
  type: RestaurantType
  openingHours: OpeningHoursInput
  phoneNumber: String
  email: String
  imageUrl: String
  isActive: Boolean
}

input OpeningHoursInput {
  monday: DailyHoursInput!
  tuesday: DailyHoursInput!
  wednesday: DailyHoursInput!
  thursday: DailyHoursInput!
  friday: DailyHoursInput!
  saturday: DailyHoursInput!
  sunday: DailyHoursInput!
}

input DailyHoursInput {
  open: String!
  close: String!
}

input AddMenuItemInput {
  name: String!
  description: String
  price: Float!
  restaurantId: ID!
  category: String!
  imageUrl: String
}

input UpdateMenuItemInput {
  name: String
  description: String
  price: Float
  category: String
  imageUrl: String
  isAvailable: Boolean
}

input OrderInput {
  restaurantId: ID!
  userId: ID!
  items: [OrderItemInput!]!
  totalAmount: Float!
  deliveryAddress: AddressInput!
  instructions: String
  status: OrderStatus
  isPaid: Boolean
  paymentMethod: PaymentMethod
  delivererId: ID! # Added delivererId field
}

input AddressInput {
  address: String!
  latitude: Float!
  longitude: Float!
}

input OrderItemInput {
  menuItemId: ID!
  quantity: Int!
}

input CreateDelivererInput {
  vehicleId: ID
  isAvailable: Boolean
  currentLocation: String
  zone: String
  profilePicture: String
}
